# Section 3 notebook

# Calculate the coef and intercept of mutivariate data set


In [1]:
# Calculate the coef and intercept of mutivariate data set

import numpy as np
from sklearn.linear_model import LinearRegression

array_y = np.array([30, 55, 20, 50])
arr2d_x = np.array([[68, 15], [78, 18], [53, 10], [60, 18]])
print(array_y)
print(arr2d_x)
reg = LinearRegression()
reg.fit(arr2d_x, array_y)
print(reg.coef_)
print(reg.intercept_)

[30 55 20 50]
[[68 15]
 [78 18]
 [53 10]
 [60 18]]
[0.0354346  4.05297392]
-25.352242573296223


In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

arr2d_data = np.loadtxt("data1.csv", delimiter=",")
array_y = arr2d_data[:, 0]
array_x = arr2d_data[:, 1]
print(array_y)
print(arr2d_x)
reg = LinearRegression()
reg.fit(arr2d_x, array_y)
print(reg.coef_)
print(reg.intercept_)


[30. 55. 20. 50.]
[[68 15]
 [78 18]
 [53 10]
 [60 18]]
[0.0354346  4.05297392]
-25.352242573296223


## Exercise

In [7]:
import numpy as np
from sklearn.linear_model import LinearRegression

arr2d_data = np.loadtxt("data2.csv", delimiter=",")
array_y = arr2d_data[:, 0]
arr2d_x = arr2d_data[:, 1:]

reg = LinearRegression()
reg.fit(arr2d_x, array_y)
print(f"{reg.intercept_:.2f}")
print(f"{reg.coef_[0]:.2f}")
print(f"{reg.coef_[1]:.2f}")
print(f"{reg.coef_[2]:.2f}")


3.05
-1.99
1.01
2.01


# Converting qualitative Variables to quantitative using Python

In [5]:
from sklearn.datasets import load_svmlight_file


list2d_data = [['Male', "O"], ["Female", "A"], ["Female", "AB"] ,["Male", "B"]]
list2d_x = []

for list_row in list2d_data:
    if list_row[0] == "Male":
        list_x = [0]
    else:
        list_x = [1]
        
    if list_row[1] == "A":
        list_x += [1, 0, 0]
    elif list_row[1] == "B":
        list_x += [0, 1, 0]
    elif list_row[1] == "O":
        list_x += [0, 0, 1]
    else:
        list_x += [0, 0, 0]
    
    print(list_row, '->', list_x)
    list2d_x += [list_x]
    
print(list2d_x)

['Male', 'O'] -> [0, 0, 0, 1]
['Female', 'A'] -> [1, 1, 0, 0]
['Female', 'AB'] -> [1, 0, 0, 0]
['Male', 'B'] -> [0, 0, 1, 0]
[[0, 0, 0, 1], [1, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]]
